### ISSUE TITLE
Aulaa

### ISSUE THREAD

**Issue by luanschimidel** [ocefpaf/waves_and_tides#1]
Boa tarde felipe, estava sou estudante de oceanografia da uerj, estava utilizando da biblioteca folium e quase por acidente achei seu perfil. Gostaria primeiramente de te agradecer por tanto conteúdo voltado pra área. e em segundo, como posso  vizualizar as aulas desse modulo de ondas e correntes?? Po

**Comment by ocefpaf** [comment]
Essas aulas são bem antigas e as partes de quadro não estão no repositório.
O que está aí é um misto de latex e markdown. De uma navegada nas pastas para ver o conteúdo. Para compilar em slides tem instruções no README. Boa sorte.
